# cuda
cuda_index: 0
seed: 45

# path 
lang: zh
annotation_dir: data/dataset/annotation
json_path: data/dataset/jsons
preprocessed_dir: data/preprocessed
target_dir: data/save

bert-en:
  bert_path: FacebookAI/roberta-large
  cls: '<s>'
  sep: '</s>'
  unk: '<unk>'
  pad: '<pad>'
# bert-en:
#   bert_path: bert-large-cased
#   cls: '[CLS]'
#   sep: '[SEP]'
#   unk: '[UNK]'
#   pad: '[PAD]'

bert-zh:
  bert_path: hfl/chinese-roberta-wwm-ext
  cls: '[CLS]'
  sep: '[SEP]'
  unk: '[UNK]'
  pad: '[PAD]'

unkown_tokens: 'ğŸ”â€”ğŸ›ğŸ™‰ğŸ™„ğŸ”¨ğŸ†ğŸ†”ğŸ‘ŒğŸ‘€ğŸ¥ºå†–ğŸŒšğŸ™ˆğŸ˜­ğŸğŸ˜…ğŸ’©å°›ç¡Œç³‡ğŸ’°ğŸ´ğŸ™ŠğŸ’¯â­ğŸ¶ğŸŸğŸ™ğŸ˜„ğŸ»ğŸ“¶ğŸ®ğŸºâŒğŸ¤”ğŸğŸ¸ğŸ™ƒğŸ¤£ğŸ†ğŸ˜‚ğŸŒš'
max_length: 512

# parameter 
epoch_size: 60
patience: 20
batch_size: 2
lr: 0.0001
expert_lr : 0.0001
bert_lr: 0.00001
max_grad_norm: 1
warmup_proportion: 0.1
gradient_accumulation_steps: 1
adam_epsilon: 1e-7
warmup_steps: 350
weight_decay: 0.1
dropout: 0.2

eps: 1e-9
inner_dim: 256
output_dim: 256
k_alpha : 0.1
k_beta : 0.2

# dict 
bio_mode: 'OBIES'
asp_type: 'Aspect'
tgt_type: 'Target'
opi_type: 'Opinion'

polarity_dict:
  O: 0
  pos: 1
  neg: 2
  other: 3


# You can set this value to 'False' to save GPU memory, but the performance may decrease.
use_rope: True

loss_weight:
  ent: 2
  rel: 9
  pol: 6
